### ISSUE TITLE
ADE chrashes if empty media queries exists

### ISSUE THREAD

**Issue by finanzer** [dvschultz/99problems#44]
If in css file empty media queries exists, then ADE (tested with 2.0 and 4.0) and readers (e.g. tolino) or software (blue fire reader) with adobe engine chrashes. Here an example file:

``` css
@font-face { 
    font-family : "Gentium"; 
    font-weight : normal; 
    font-style: normal; 
    src: url("../Fonts/GentiumPlus-R.ttf"); 
}

@media amzn-kf8
{
}

@media not amzn-mobi
{
}
```

Repair is naturally easy: remove the empty media queries
